import assert from 'node:assert/strict';
import { searchMembers, memberPage } from '../services/memberDirectory';
import { paymentHistoryRows, memberEvidence, memberStatus, accountStatus } from '../services/memberPresentation';
import { User, Payment, PaymentReceipt } from '../types';
import { adminAreas, findAdminArea, AdminTab } from '../components/adminNavigation';
const users = Array.from({ length: 137 }, (_, i) => ({ uid: `u${i}`, name: `Miembro ${String(i).padStart(3, '0')}`, email: `m${i}@example.test`, active: true, role: 'member', groupId: 'test', joinDate: `2026-09-${String(i % 28 + 1).padStart(2, '0')}`, profileEditable: true } as User));
users[42] = { ...users[42], name: 'José Ríos', degree: 'maestro', lodgeRole: 'tesorero' };
const original = users.map(u => u.uid);
assert.deepEqual(searchMembers(users, 'jose rios', 'name', {}).map(u => u.uid), ['u42']);
assert.equal(searchMembers(users, 'tesorero maestro', 'name', {}).length, 1);
assert.equal(searchMembers(users, 'm42@', 'name', {}).length, 1);
assert.equal(searchMembers(users, 'no existe', 'name', {}).length, 0);
assert.equal(searchMembers(users, '', 'debt', { u5: { totalDebt: 400 } })[0].uid, 'u5');
const sorted = searchMembers(users, '', 'newest', {});
assert.equal(sorted[0].joinDate, '2026-09-28');
assert.deepEqual(users.map(u => u.uid), original, 'search must not reorder the shared member list');
const pages = Array.from({ length: 6 }, (_, i) => memberPage(users, i + 1, 25));
assert.equal(pages[5].rows.length, 12);
assert.equal(new Set(pages.flatMap(page => page.rows).map(u => u.uid)).size, 137);
assert.equal(memberPage(users.slice(0, 1), 6, 25).current, 1, 'clamp after data shrinks');
assert.deepEqual(memberPage([], 1, 25), { rows: [], current: 1, pages: 1 });
const expected: AdminTab[] = ['dashboard', 'requests', 'users', 'fees', 'attendance', 'trivia', 'treasury', 'projects', 'notices', 'tasks', 'banks', 'visits', 'payment-matrix', 'create-user', 'manual-merge', 'receipts', 'debt-notify'];
assert.deepEqual(adminAreas.flatMap(a => a.items.map(i => i.id)).sort(), expected.sort());
for (const tab of expected) assert.ok(findAdminArea(tab));
console.log('Directory and navigation tests passed: 137 members, search, sort, all pages and all 17 screens.');

const legacy = { period: '2026-09', amount: 100, extraAmount: 50, extraDescription: 'Evento', paid: 120 } as Payment;
const rows = paymentHistoryRows([legacy]);
assert.deepEqual(rows.map(row => [row.concept, row.paid, row.balance]), [['Cuota mensual', 100, 0], ['Evento', 20, 30]]);
const individual = { ...legacy, paid: 130, extraFees: [{ id: 'fee', description: 'Evento', amount: 50, paid: 30, forgiven: true }] } as Payment;
assert.equal(paymentHistoryRows([individual])[1].balance, 0);
assert.equal(paymentHistoryRows([individual])[1].forgiven, true);
assert.equal(legacy.paidRegular, undefined, 'history presentation must not mutate legacy data');
assert.equal(memberStatus({ ...users[0], active: false, leaveDate: '2026-09-01' }), 'Inactivo');
assert.equal(memberStatus({ ...users[0], active: false }), 'Pendiente');
assert.equal(accountStatus({ ...users[0], uid: 'temp_1' }), 'Sin cuenta vinculada');

const receipt = {id:'proof',periods:['2026-08','2026-09'],transferDate:'2026-09-15',status:'pending',receiptType:'cuota_mensual',amount:999,receiptImageUrl:'https://example.test/a.pdf',receiptImageUrls:['https://example.test/a.pdf','https://example.test/b.jpg']} as PaymentReceipt;
const proofLedger = {...legacy,adminReceiptUrl:'https://example.test/admin.jpg',receiptImageBase64:'data:image/png;base64,test'};
const before = JSON.stringify([proofLedger,receipt]);
const evidence = memberEvidence([proofLedger],[receipt]);
assert.equal(evidence.length,2);
assert.equal(evidence[0].urls.length,2,'deduplicate legacy first URL without dropping other attachments');
assert.deepEqual(evidence[0].periods,['2026-08','2026-09']);
assert.equal(evidence[1].urls.length,2,'include both admin attachment formats');
assert.equal(paymentHistoryRows([proofLedger])[1].balance,30,'pending evidence must not reduce debt');
assert.equal(before,JSON.stringify([proofLedger,receipt]));
assert.equal(memberEvidence([],[{...receipt,status:'rejected',receiptImageUrl:'',receiptImageUrls:[]}])[0].status,'rejected');
console.log('Member evidence tests passed: multiple periods/files, both admin formats, statuses, no duplicate accounting or mutation.');
