import React, { useEffect, useRef, useState } from 'react';
import type { Payment, User } from '../types';
import type { MemberSort } from '../services/memberDirectory';
import { memberPage } from '../services/memberDirectory';
import { accountStatus, degreeLabel, memberMoney, memberStatus, MemberStats, roleLabel } from '../services/memberPresentation';
import MemberDetail, { MemberActions } from './MemberDetail';
export interface MemberFilters { query: string; sort: MemberSort; role: string; status: string; start: string; end: string; }
interface Props {
  members: User[]; allMembers: User[]; currentUser: User; stats: Record<string, MemberStats>; statsLoading: boolean; readOnly: boolean;
  filters: MemberFilters; onFilters: (change: Partial<MemberFilters>) => void;
  actions: MemberActions; loadHistory: (uid: string) => Promise<Payment[]>;
  onCreate: () => void; onRequests: () => void; pendingCount: number; onExport: () => Promise<void>; onRefresh: () => Promise<void>;
}
export default function MemberManagement({ members, allMembers, currentUser, stats, statsLoading, readOnly, filters, onFilters, actions, loadHistory, onCreate, onRequests, pendingCount, onExport, onRefresh }: Props) {
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(25);
  const [financial, setFinancial] = useState(false);
  const [showFilters, setShowFilters] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [revision, setRevision] = useState(0);
  const [exporting, setExporting] = useState(false);
  const listRef = useRef<HTMLDivElement>(null);
  const selected = allMembers.find(member => member.uid === selectedId);
  const directory = memberPage(members, page, size);
  useEffect(() => { setPage(1); }, [filters.query, filters.role, filters.status, filters.sort, size]);
  useEffect(() => { if (selectedId && !selected) setSelectedId(null); }, [selectedId, selected]);
  useEffect(() => { setRevision(value => value + 1); }, [stats]);
  const close = () => { setSelectedId(null); requestAnimationFrame(() => listRef.current?.querySelector<HTMLButtonElement>(`button[data-member-id="${CSS.escape(selectedId || '')}"]`)?.focus()); };
  useEffect(() => {
    if (!selectedId) return;
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelectedId(null); };
    window.addEventListener('keydown', escape);
    return () => window.removeEventListener('keydown', escape);
  }, [selectedId]);
  const amount = (member: User, field: keyof MemberStats) => statsLoading ? '…' : stats[member.uid]?.[field] == null ? '—' : memberMoney(stats[member.uid][field]!);
  const controls = 'block w-full mt-1 rounded-lg border border-logia-700 bg-logia-900 p-3 text-sm text-white';
  const activeFilters = [filters.role !== 'all', filters.status !== 'active', Boolean(filters.start), Boolean(filters.end)].filter(Boolean).length;
  const activeCount = allMembers.filter(member => member.active).length;
  return <section className="space-y-4 min-w-0" aria-label="Gestión de miembros">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-lg">Directorio de miembros</h3><p className="text-xs text-gray-400 mt-1">{allMembers.length} registrados · {activeCount} activos · {pendingCount} pendientes</p></div><div className="flex flex-wrap gap-2"><button disabled={readOnly} onClick={onCreate} className="bg-indigo-600 rounded-lg px-4 py-3 text-sm disabled:opacity-40">Crear miembro</button><button onClick={onRequests} className="border border-logia-700 rounded-lg px-3 py-3 text-sm">Solicitudes ({pendingCount})</button><button disabled={readOnly} onClick={actions.link} className="border border-logia-700 rounded-lg px-3 py-3 text-sm disabled:opacity-40">Vincular cuenta</button></div></div>
    <div className="bg-logia-800 border border-logia-700 rounded-xl p-3 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-[1fr_auto] gap-2"><label className="text-xs text-gray-400">Buscar miembro<input type="search" value={filters.query} onChange={event => onFilters({ query: event.target.value })} placeholder="Nombre, correo, grado o cargo" className={controls} /></label><button onClick={() => setShowFilters(value => !value)} aria-expanded={showFilters} className="rounded-lg border border-logia-700 px-4 py-3 text-sm sm:self-end">Filtros{activeFilters ? ` (${activeFilters})` : ''}</button></div>
      {showFilters && <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3"><label className="text-xs text-gray-400">Estado<select value={filters.status} onChange={event => onFilters({status:event.target.value})} className={controls}><option value="active">Activos</option><option value="all">Todos</option><option value="inactive">Inactivos y pendientes</option></select></label><label className="text-xs text-gray-400">Rol<select value={filters.role} onChange={event => onFilters({role:event.target.value})} className={controls}><option value="all">Todos</option><option value="member">Miembro</option><option value="admin">Administrador</option><option value="viewer">Observador</option><option value="master">Maestro del sistema</option></select></label><label className="text-xs text-gray-400">Saldos desde<input type="month" value={filters.start} onChange={event => onFilters({start:event.target.value})} className={controls} /></label><label className="text-xs text-gray-400">Saldos hasta<input type="month" value={filters.end} onChange={event => onFilters({end:event.target.value})} className={controls} /></label><button onClick={() => onFilters({ query:'', role:'all', status:'active', start:'', end:'' })} className="text-sm text-indigo-300 text-left p-2">Restablecer filtros</button></div>}
      <div className="flex flex-wrap gap-3 justify-between items-center"><label className="text-xs text-gray-400">Ordenar<select value={filters.sort} onChange={event => onFilters({sort:event.target.value as MemberSort})} className={controls}><option value="name">Nombre A–Z</option><option value="debt">Mayor adeudo</option><option value="newest">Registro más reciente</option></select></label><div className="flex gap-2"><button disabled={statsLoading} onClick={async () => { await onRefresh(); setRevision(value=>value+1); }} className="border border-logia-700 rounded-lg px-3 py-3 text-xs disabled:opacity-40">Actualizar</button><button disabled={exporting || members.length === 0} onClick={async () => { setExporting(true); try { await onExport(); } finally { setExporting(false); } }} className="border border-logia-700 rounded-lg px-3 py-3 text-xs disabled:opacity-40">{exporting ? 'Exportando…' : 'Exportar CSV'}</button></div></div>
      <p className="text-xs text-gray-400">{filters.start || filters.end ? `Saldos: ${filters.start || 'inicio'} a ${filters.end || 'actualidad'}` : 'Saldos de todo el historial'}{statsLoading ? ' · Actualizando saldos…' : ''}</p>
    </div>
    <div className={`grid gap-4 min-w-0 ${selected ? 'lg:grid-cols-[minmax(0,1fr)_360px]' : ''}`}>
      <div className="min-w-0" ref={listRef}>
        <label className="hidden md:flex items-center gap-2 text-xs text-gray-400 mb-3"><input type="checkbox" checked={financial} onChange={event=>setFinancial(event.target.checked)} />Mostrar columnas financieras</label>
        <div className="md:hidden space-y-2">{directory.rows.map(member => <button data-member-id={member.uid} key={member.uid} onClick={() => setSelectedId(member.uid)} className="w-full text-left rounded-xl border border-logia-700 bg-logia-800 p-4 flex gap-3 items-start min-w-0"><span className="h-10 w-10 shrink-0 flex items-center justify-center rounded-full bg-indigo-900 text-indigo-200 font-bold" aria-hidden="true">{member.name.charAt(0).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="font-semibold block break-words">{member.name}</span><span className="text-xs text-gray-400 block truncate">{member.email}</span><span className="flex flex-wrap gap-2 text-xs mt-2"><span className={member.active ? 'text-green-300' : 'text-amber-300'}>{memberStatus(member)}</span><span className="text-gray-400">{degreeLabel(member.degree)}</span></span><span className="text-xs text-gray-400 block mt-2">{accountStatus(member)}</span><span className="text-sm block mt-2">Adeudo: <strong className="text-red-300">{amount(member,'totalDebt')}</strong></span></span><span className="text-gray-400 shrink-0" aria-hidden="true">›</span></button>)}</div>
        <div className="hidden md:block overflow-x-auto rounded-xl border border-logia-700 bg-logia-800"><table className={`w-full text-left text-sm ${financial ? 'min-w-[1080px]' : 'min-w-[620px]'}`}><thead className="bg-logia-900 text-xs text-gray-400"><tr><th className="p-3">Miembro</th><th className="p-3">Estado y cuenta</th><th className="p-3">Grado / rol</th>{financial && <><th className="p-3 text-right">Cuota mensual</th><th className="p-3 text-right">Cuota extra</th><th className="p-3 text-right">Pagado mensual</th><th className="p-3 text-right">Pagado extra</th></>}<th className="p-3 text-right">Adeudo</th><th className="p-3">Detalle</th></tr></thead><tbody className="divide-y divide-logia-700">{directory.rows.map(member => <tr key={member.uid} className={selectedId === member.uid ? 'bg-indigo-900/30' : 'hover:bg-logia-700/40'}><td className="p-3 max-w-[260px]"><span className="block font-semibold truncate" title={member.name}>{member.name}</span><span className="block text-xs text-gray-400 truncate" title={member.email}>{member.email}</span></td><td className="p-3"><span className={`block text-xs ${member.active ? 'text-green-300' : 'text-amber-300'}`}>{memberStatus(member)}</span><span className="block text-xs text-gray-400 mt-1">{accountStatus(member)}</span></td><td className="p-3 text-xs"><span className="block">{degreeLabel(member.degree)}</span><span className="text-gray-400">{roleLabel(member.role)}</span></td>{financial && (['totalBilledRegular','totalBilledExtra','totalPaidRegular','totalPaidExtra'] as const).map(field => <td key={field} className="p-3 text-right whitespace-nowrap">{amount(member,field)}</td>)}<td className="p-3 text-right font-semibold text-red-300 whitespace-nowrap">{amount(member,'totalDebt')}</td><td className="p-3"><button data-member-id={member.uid} onClick={() => setSelectedId(member.uid)} className="rounded-lg border border-indigo-700 px-3 py-3 text-xs text-indigo-300 whitespace-nowrap" aria-label={`Ver ficha de ${member.name}`}>Ver ficha</button></td></tr>)}</tbody></table></div>
        {!members.length && <div className="text-center border border-dashed border-logia-700 rounded-xl p-6"><p className="text-gray-400">No hay miembros con estos filtros.</p><button onClick={() => onFilters({query:'',role:'all',status:'all'})} className="text-indigo-300 p-3 mt-2">Ver todos los miembros</button></div>}
        <div className="flex flex-wrap justify-between items-center gap-3 py-4 text-xs text-gray-400" aria-live="polite"><span>{members.length ? (directory.current-1)*size+1 : 0}–{Math.min(directory.current*size,members.length)} de {members.length} miembros</span><label>Por página <select value={size} onChange={event=>setSize(Number(event.target.value))} className="rounded-lg bg-logia-800 border border-logia-700 p-3"><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><div className="flex gap-2 items-center"><button disabled={directory.current===1} onClick={()=>setPage(directory.current-1)} className="rounded-lg border border-logia-700 px-3 py-3 disabled:opacity-30">Anterior</button><span>{directory.current} / {directory.pages}</span><button disabled={directory.current===directory.pages} onClick={()=>setPage(directory.current+1)} className="rounded-lg border border-logia-700 px-3 py-3 disabled:opacity-30">Siguiente</button></div></div>
        <p className="text-xs text-gray-500">El CSV incluye todos los resultados, aunque estén en otras páginas. Buscar y cambiar de página solo afecta al directorio.</p>
      </div>
      {selected && <MemberDetail member={selected} currentUser={currentUser} stats={stats[selected.uid]} statsLoading={statsLoading} readOnly={readOnly} actions={actions} loadHistory={loadHistory} revision={revision} onClose={close} />}
    </div>
  </section>;
}
