import React, { useEffect, useMemo, useState } from 'react';
import type { TreasuryEntry } from '../types';
import { emptyTreasuryFilters, filterTreasuryReport, reportClassLabel, reportConcept, reportPeriod, reportProjects, treasuryReportCsv, treasuryReportTotals, type TreasuryReportFilters } from '../services/treasuryReport';

interface Props {
  entries: TreasuryEntry[]; groupId: string; readOnly: boolean; loading?: boolean;
  onRefresh: ()=>void;
  onEdit: (entry: TreasuryEntry,event: React.MouseEvent<HTMLButtonElement>)=>void;
  onDelete: (id: string,event: React.MouseEvent<HTMLButtonElement>)=>void;
}
const field='w-full min-w-0 bg-logia-900 border border-logia-700 rounded-lg p-2 text-sm text-white';
const money=(value:number)=>value.toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const monthLabel=(period:string)=>new Date(`${period}-01T12:00:00Z`).toLocaleDateString('es-MX',{month:'long',year:'numeric',timeZone:'UTC'});
const PAGE_SIZE=25;

export default function TreasuryReport({entries,groupId,readOnly,loading,onRefresh,onEdit,onDelete}:Props) {
  const [filters,setFilters]=useState(emptyTreasuryFilters);const [page,setPage]=useState(0);
  const update=(change:Partial<TreasuryReportFilters>)=>{setFilters(previous=>({...previous,...change}));setPage(0);};
  const periods=useMemo(()=>Array.from(new Set(entries.map(entry=>reportPeriod(entry,filters.basis)).filter(Boolean))).sort().reverse(),[entries,filters.basis]);
  const years=Array.from(new Set(periods.map(period=>period.slice(0,4))));
  const concepts=Array.from(new Set(entries.filter(entry=>entry.quotaKind==='extra').map(reportConcept))).sort((a,b)=>a.localeCompare(b,'es'));
  const projects=Array.from(new Map(entries.flatMap(reportProjects).map(project=>[project.id,project])).values()).sort((a,b)=>a.name.localeCompare(b.name,'es'));
  const filtered=useMemo(()=>filterTreasuryReport(entries,filters),[entries,filters]);
  const totals=treasuryReportTotals(filtered);const maxPage=Math.max(0,Math.ceil(filtered.length/PAGE_SIZE)-1);
  const current=Math.min(page,maxPage);const rows=filtered.slice(current*PAGE_SIZE,(current+1)*PAGE_SIZE);
  useEffect(()=>setPage(0),[groupId]);
  const download=()=>{
    const blob=new Blob([treasuryReportCsv(filtered,filters.basis)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);
    const link=document.createElement('a');link.href=url;link.download=`tesoreria_${groupId}_${filters.month || filters.year || 'todos'}_${filters.incomeClass}.csv`;link.click();URL.revokeObjectURL(url);
  };
  const actions=(entry:TreasuryEntry)=>entry.quickStatus ? <button disabled={readOnly} type="button" className="p-2 text-indigo-300 disabled:opacity-40" onClick={()=>window.dispatchEvent(new CustomEvent('open-quick-finance',{detail:{id:entry.id}}))}>Ver / completar captura</button> : entry.quotaKind || entry.id.startsWith('quota_') ? <button disabled={readOnly} type="button" className="p-2 text-yellow-300 disabled:opacity-40" onClick={event=>onEdit(entry,event)}>Corregir pago / fecha</button> : <div className="flex gap-2"><button disabled={readOnly} type="button" className="p-2 text-gray-300 disabled:opacity-40" onClick={event=>onEdit(entry,event)}>Editar</button><button disabled={readOnly} type="button" className="p-2 text-red-300 disabled:opacity-40" onClick={event=>onDelete(entry.id,event)}>Eliminar</button></div>;
  return <section aria-label="Reporte mensual de tesorería" className="bg-logia-800 rounded-xl border border-logia-700 shadow-lg overflow-hidden">
    <div className="p-4 border-b border-logia-700 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold text-white">Historial de Movimientos (Incluye Cuotas)</h3><div className="flex flex-wrap gap-2"><button type="button" disabled={loading} onClick={onRefresh} className="text-sm p-2 text-indigo-300 disabled:opacity-40">Actualizar reporte</button><button type="button" disabled={loading || filtered.length===0} onClick={download} className="text-sm bg-green-700 px-3 py-2 rounded text-white disabled:opacity-40">Descargar CSV filtrado</button></div></div>
      <p className="text-xs text-gray-400">El mes de cuota viene de la matriz de pagos. La fecha de registro es la del acumulado mensual y puede incluir varios abonos. Los movimientos manuales usan su propio mes. El CSV incluye todos los resultados filtrados.</p>
      <div className="grid grid-cols-1 min-[380px]:grid-cols-2 lg:grid-cols-4 gap-3">
        <label className="block text-sm">Mes según<select aria-label="Mes según" className={field} value={filters.basis} onChange={event=>update({basis:event.target.value as TreasuryReportFilters['basis'],year:'',month:''})}><option value="quota">Cuota / movimiento</option><option value="date">Fecha de registro</option></select></label>
        <label className="block text-sm">Año<select aria-label="Año del reporte" className={field} value={filters.year} onChange={event=>update({year:event.target.value,month:''})}><option value="">Todos los años</option>{years.map(year=><option key={year} value={year}>{year}</option>)}</select></label>
        <label className="block text-sm">Mes<select aria-label="Mes del reporte" className={field} value={filters.month} onChange={event=>update({month:event.target.value})}><option value="">Todos los meses</option>{periods.filter(period=>!filters.year || period.startsWith(filters.year+'-')).map(period=><option key={period} value={period}>{monthLabel(period)}</option>)}</select></label>
        <label className="block text-sm">Tipo<select aria-label="Tipo de movimiento" className={field} value={filters.direction} onChange={event=>update({direction:event.target.value as TreasuryReportFilters['direction'],incomeClass:'all',concept:''})}><option value="all">Ingresos y gastos</option><option value="income">Ingresos</option><option value="expense">Gastos</option></select></label>
        <label className="block text-sm">Clase de ingreso<select aria-label="Clase de ingreso" className={field} disabled={filters.direction==='expense'} value={filters.incomeClass} onChange={event=>update({incomeClass:event.target.value as TreasuryReportFilters['incomeClass'],concept:''})}><option value="all">Todas las clases</option><option value="regular">Cuota normal</option><option value="extra">Cuota extraordinaria</option><option value="other">Otros ingresos</option><option value="unclassified">Cuotas sin desglose</option></select></label>
        <label className="block text-sm">Cuota extraordinaria<select aria-label="Concepto de cuota extraordinaria" className={field} disabled={filters.direction==='expense' || (filters.incomeClass!=='all' && filters.incomeClass!=='extra')} value={filters.concept} onChange={event=>update({concept:event.target.value,incomeClass:event.target.value?'extra':filters.incomeClass})}><option value="">Todos los conceptos</option>{concepts.map(concept=><option key={concept} value={concept}>{concept}</option>)}</select></label>
        <label className="block text-sm">Proyecto<select aria-label="Proyecto del movimiento" className={field} value={filters.project} onChange={event=>update({project:event.target.value})}><option value="">Todos los proyectos</option><option value="unlinked">Sin proyecto</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
        <label className="block text-sm">Buscar<input aria-label="Buscar miembro o concepto en tesorería" className={field} placeholder="Miembro o concepto" value={filters.search} onChange={event=>update({search:event.target.value})}/></label>
      </div>
      <button type="button" onClick={()=>{setFilters(emptyTreasuryFilters());setPage(0);}} className="text-sm text-indigo-300 p-2">Limpiar filtros</button>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-sm" aria-label="Totales filtrados">
        {[['Cuota normal',totals.regular],['Cuota extraordinaria',totals.extra],['Ingresos',totals.income],['Gastos',totals.expense]].map(([label,value])=><div key={String(label)} className="p-3 rounded-lg bg-logia-900 min-w-0"><span className="block text-xs text-gray-400">{label}</span><strong className="block break-words">{money(Number(value))}</strong></div>)}
      </div>
      <p className="text-sm text-gray-300">Balance filtrado: <strong>{money(totals.balance)}</strong> · {filtered.length} registros</p>
      {loading && <p role="status" className="text-indigo-300">Actualizando tesorería…</p>}
    </div>
    {!filtered.length && !loading && <p className="p-6 text-gray-400">No hay registros para estos filtros.</p>}
    <div className="hidden md:block overflow-x-auto"><table className="w-full text-left text-sm text-gray-300" aria-label="Movimientos de tesorería"><thead className="bg-logia-900 text-xs uppercase text-gray-500"><tr>{['Mes','Fecha de registro','Tipo / clase','Miembro','Concepto','Proyecto','Monto','Acción'].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-logia-700">{rows.map(entry=><tr key={entry.id}><td className="p-3 whitespace-nowrap">{reportPeriod(entry,filters.basis) || 'Sin mes'}</td><td className="p-3 whitespace-nowrap">{entry.date}</td><td className="p-3">{entry.type==='income'?'Ingreso':'Gasto'}<span className="block text-xs text-indigo-300">{reportClassLabel(entry)}</span></td><td className="p-3">{entry.memberName || '—'}</td><td className="p-3">{reportConcept(entry)}{entry.quickStatus==='pending' && <span className="block text-xs text-amber-300">Pendiente de completar</span>}{entry.reportNote && <p className="text-xs text-gray-500 mt-1">{entry.reportNote}</p>}</td><td className="p-3">{reportProjects(entry).map(project=>project.name).join(' / ') || 'Sin proyecto'}</td><td className={`p-3 whitespace-nowrap font-bold ${entry.type==='income'?'text-green-300':'text-red-300'}`}>{money(entry.amount)}</td><td className="p-3 text-xs">{actions(entry)}</td></tr>)}</tbody></table></div>
    <div className="md:hidden p-3 space-y-3">{rows.map(entry=><article key={entry.id} aria-label={`${entry.memberName || 'Movimiento'} · ${reportClassLabel(entry)} · ${reportPeriod(entry,filters.basis) || 'Sin mes'}`} className="p-3 rounded-lg border border-logia-700 bg-logia-900 min-w-0 break-words"><div className="flex justify-between items-start gap-2"><span className="text-sm text-indigo-300">{reportClassLabel(entry)}</span><strong className={entry.type==='income'?'text-green-300':'text-red-300'}>{money(entry.amount)}</strong></div><p className="font-semibold mt-2">{entry.memberName || (entry.type==='income'?'Ingreso manual':'Gasto')}</p><p className="text-sm">{reportConcept(entry)}</p><p className="text-xs text-gray-400 mt-2">Mes: {reportPeriod(entry,filters.basis) || 'Sin mes'} · Registro: {entry.date}</p><p className="text-xs text-gray-300 mt-1">Proyecto: {reportProjects(entry).map(project=>project.name).join(' / ') || 'Sin proyecto'}</p>{entry.quickStatus==='pending' && <p className="text-xs text-amber-300 mt-1">Pendiente de completar</p>}{entry.reportNote && <p className="text-xs text-gray-500 mt-1">{entry.reportNote}</p>}<div className="text-xs mt-2">{actions(entry)}</div></article>)}</div>
    {filtered.length>0 && <div className="p-3 border-t border-logia-700 flex flex-wrap justify-between items-center gap-2"><p className="text-xs text-gray-400">{current*PAGE_SIZE+1}–{Math.min((current+1)*PAGE_SIZE,filtered.length)} de {filtered.length} registros</p><div className="flex gap-2"><button type="button" disabled={current===0} onClick={()=>setPage(current-1)} className="p-2 rounded border border-logia-700 disabled:opacity-40">Anterior</button><button type="button" disabled={current>=maxPage} onClick={()=>setPage(current+1)} className="p-2 rounded border border-logia-700 disabled:opacity-40">Siguiente</button></div></div>}
  </section>;
}
